site_name: nimler
site_description: Erlang/Elixir NIFs in nim
site_author: wltsmrz
site_url: https://wltsmrz.github.io/nimler

repo_name: wltsmrz/nimler
repo_url: https://github.com/wltsmrz/nimler

nav:
  - Getting Started: index.md
  - Examples:
    - NumberAdder: examples/NumberAdder.md
    - PIController: examples/PIController.md
    - Nimler Tests: examples/tests.md
  - Developer Guide:
    - Nimler Modules: guide/nimler_structure.md
    - Reading and Writing Erlang terms: guide/codec.md
    - Using Resource Objects: guide/resources.md
    - Cooperating with Erlang Schedulers: guide/timeslice.md
    - Generating Elixir Modules: guide/generating_wrapper.md
  - API: api.md

theme:
  name: material
  language: en
  palette:
    primary: blue grey
    accent: light blue
  features:
    - tabs

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed


