site_name: nimler
site_description: Erlang/Elixir NIFs in nim
site_author: wltsmrz
site_url: https://wltsmrz.github.io/nimler

repo_name: wltsmrz/nimler
repo_url: https://github.com/wltsmrz/nimler

nav:
  - Getting Started: index.md
  - Examples:
    - NumberAdder: examples/NumberAdder.md
    - PIController: examples/PIController.md
    - OrderedSet: examples/OrderedSet.md
  - Developer Guide:
    - Reading and writing Erlang terms: guide/codec.md
    - Using resource objects: guide/resources.md
    - Cooperating with Erlang schedulers: guide/timeslice.md
  - API:
    - Nim docs: api.md

theme:
  name: material
  language: en
  palette:
    primary: blue grey
    accent: light blue
  features:
    - tabs

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed


