
name: CI

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-elixir@v1.2.0
      with:
          otp-version: 22.x
          elixir-version: 1.10.x
    - uses: jiro4989/setup-nim-action@v1.0.2
      with:
          nim-version: '1.2.0'
    - run: nimble test_all
